import React from 'react';
import CarItem from './CarItem'; // Import the CarItem component

function CarList({ cars, onDelete, onUpdate }) {
  return (
    <ul>
      {cars.map((car) => (
        <CarItem key={car.id} car={car} onDelete={onDelete} onUpdate={onUpdate} />
      ))}
    </ul>
  );                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
}

export default CarList;
